// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package grpc;

/** grpc 生成 */
@SuppressWarnings("all")
public final class Test {
  private static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grpc_RPCDateRequest_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_RPCDateRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
      internal_static_grpc_RPCDateResponse_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_RPCDateResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    String[] descriptorData = {
      "\n\ntest.proto\022\004grpc\"\"\n\016RPCDateRequest\022\020\n\010"
          + "userName\030\001 \001(\t\"%\n\017RPCDateResponse\022\022\n\nser"
          + "verDate\030\001 \001(\t2J\n\016RPCDateService\0228\n\007getDa"
          + "te\022\024.grpc.RPCDateRequest\032\025.grpc.RPCDateR"
          + "esponse\"\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
        descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
    internal_static_grpc_RPCDateRequest_descriptor = getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_RPCDateRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grpc_RPCDateRequest_descriptor,
            new String[] {
              "UserName",
            });
    internal_static_grpc_RPCDateResponse_descriptor = getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_RPCDateResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_grpc_RPCDateResponse_descriptor,
            new String[] {
              "ServerDate",
            });
  }

  private Test() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  public interface RPCDateRequestOrBuilder
      extends
      // @@protoc_insertion_point(interface_extends:grpc.RPCDateRequest)
      com.google.protobuf.MessageOrBuilder {

    /** <code>optional string userName = 1;</code> */
    String getUserName();
    /** <code>optional string userName = 1;</code> */
    com.google.protobuf.ByteString getUserNameBytes();
  }

  public interface RPCDateResponseOrBuilder
      extends
      // @@protoc_insertion_point(interface_extends:grpc.RPCDateResponse)
      com.google.protobuf.MessageOrBuilder {

    /** <code>optional string serverDate = 1;</code> */
    String getServerDate();
    /** <code>optional string serverDate = 1;</code> */
    com.google.protobuf.ByteString getServerDateBytes();
  }

  /**
   *
   *
   * <pre>
   * 定义请求体
   * </pre>
   *
   * Protobuf type {@code grpc.RPCDateRequest}
   */
  public static final class RPCDateRequest extends com.google.protobuf.GeneratedMessageV3
      implements
      // @@protoc_insertion_point(message_implements:grpc.RPCDateRequest)
      RPCDateRequestOrBuilder {
    public static final int USERNAME_FIELD_NUMBER = 1;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:grpc.RPCDateRequest)
    private static final RPCDateRequest DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<RPCDateRequest> PARSER =
        new com.google.protobuf.AbstractParser<RPCDateRequest>() {
          public RPCDateRequest parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new RPCDateRequest(input, extensionRegistry);
          }
        };

    static {
      DEFAULT_INSTANCE = new RPCDateRequest();
    }

    private volatile Object userName_;
    private byte memoizedIsInitialized = -1;
    // Use RPCDateRequest.newBuilder() to construct.
    private RPCDateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private RPCDateRequest() {
      userName_ = "";
    }

    private RPCDateRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default:
              {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
            case 10:
              {
                String s = input.readStringRequireUtf8();

                userName_ = s;
                break;
              }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return Test.internal_static_grpc_RPCDateRequest_descriptor;
    }

    public static RPCDateRequest parseFrom(com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static RPCDateRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static RPCDateRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static RPCDateRequest parseFrom(
        byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static RPCDateRequest parseFrom(java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static RPCDateRequest parseFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static RPCDateRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static RPCDateRequest parseDelimitedFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static RPCDateRequest parseFrom(com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static RPCDateRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(RPCDateRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static RPCDateRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<RPCDateRequest> parser() {
      return PARSER;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    protected FieldAccessorTable internalGetFieldAccessorTable() {
      return Test.internal_static_grpc_RPCDateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(RPCDateRequest.class, Builder.class);
    }

    /** <code>optional string userName = 1;</code> */
    public String getUserName() {
      Object ref = userName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }

    /** <code>optional string userName = 1;</code> */
    public com.google.protobuf.ByteString getUserNameBytes() {
      Object ref = userName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      if (!getUserNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userName_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userName_);
      }
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof RPCDateRequest)) {
        return super.equals(obj);
      }
      RPCDateRequest other = (RPCDateRequest) obj;

      boolean result = true;
      result = result && getUserName().equals(other.getUserName());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public Builder newBuilderForType() {
      return newBuilder();
    }

    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    @Override
    public com.google.protobuf.Parser<RPCDateRequest> getParserForType() {
      return PARSER;
    }

    public RPCDateRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

    /**
     *
     *
     * <pre>
     * 定义请求体
     * </pre>
     *
     * Protobuf type {@code grpc.RPCDateRequest}
     */
    public static final class Builder
        extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
        implements
        // @@protoc_insertion_point(builder_implements:grpc.RPCDateRequest)
        RPCDateRequestOrBuilder {
      private Object userName_ = "";

      // Construct using grpc.Test.RPCDateRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return Test.internal_static_grpc_RPCDateRequest_descriptor;
      }

      protected FieldAccessorTable internalGetFieldAccessorTable() {
        return Test.internal_static_grpc_RPCDateRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(RPCDateRequest.class, Builder.class);
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
      }

      public Builder clear() {
        super.clear();
        userName_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return Test.internal_static_grpc_RPCDateRequest_descriptor;
      }

      public RPCDateRequest getDefaultInstanceForType() {
        return RPCDateRequest.getDefaultInstance();
      }

      public RPCDateRequest build() {
        RPCDateRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public RPCDateRequest buildPartial() {
        RPCDateRequest result = new RPCDateRequest(this);
        result.userName_ = userName_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return super.clone();
      }

      public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
        return super.setField(field, value);
      }

      public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field, int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }

      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
        return super.addRepeatedField(field, value);
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RPCDateRequest) {
          return mergeFrom((RPCDateRequest) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RPCDateRequest other) {
        if (other == RPCDateRequest.getDefaultInstance()) return this;
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RPCDateRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RPCDateRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      /** <code>optional string userName = 1;</code> */
      public String getUserName() {
        Object ref = userName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }

      /** <code>optional string userName = 1;</code> */
      public Builder setUserName(String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        userName_ = value;
        onChanged();
        return this;
      }

      /** <code>optional string userName = 1;</code> */
      public com.google.protobuf.ByteString getUserNameBytes() {
        Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /** <code>optional string userName = 1;</code> */
      public Builder setUserNameBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        userName_ = value;
        onChanged();
        return this;
      }

      /** <code>optional string userName = 1;</code> */
      public Builder clearUserName() {

        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }

      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      // @@protoc_insertion_point(builder_scope:grpc.RPCDateRequest)
    }
  }

  /**
   *
   *
   * <pre>
   * 定义相应内容
   * </pre>
   *
   * Protobuf type {@code grpc.RPCDateResponse}
   */
  public static final class RPCDateResponse extends com.google.protobuf.GeneratedMessageV3
      implements
      // @@protoc_insertion_point(message_implements:grpc.RPCDateResponse)
      RPCDateResponseOrBuilder {
    public static final int SERVERDATE_FIELD_NUMBER = 1;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:grpc.RPCDateResponse)
    private static final RPCDateResponse DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<RPCDateResponse> PARSER =
        new com.google.protobuf.AbstractParser<RPCDateResponse>() {
          public RPCDateResponse parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new RPCDateResponse(input, extensionRegistry);
          }
        };

    static {
      DEFAULT_INSTANCE = new RPCDateResponse();
    }

    private volatile Object serverDate_;
    private byte memoizedIsInitialized = -1;
    // Use RPCDateResponse.newBuilder() to construct.
    private RPCDateResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private RPCDateResponse() {
      serverDate_ = "";
    }

    private RPCDateResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default:
              {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
            case 10:
              {
                String s = input.readStringRequireUtf8();

                serverDate_ = s;
                break;
              }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return Test.internal_static_grpc_RPCDateResponse_descriptor;
    }

    public static RPCDateResponse parseFrom(com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static RPCDateResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static RPCDateResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static RPCDateResponse parseFrom(
        byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static RPCDateResponse parseFrom(java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static RPCDateResponse parseFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static RPCDateResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static RPCDateResponse parseDelimitedFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static RPCDateResponse parseFrom(com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static RPCDateResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(RPCDateResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static RPCDateResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<RPCDateResponse> parser() {
      return PARSER;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    protected FieldAccessorTable internalGetFieldAccessorTable() {
      return Test.internal_static_grpc_RPCDateResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(RPCDateResponse.class, Builder.class);
    }

    /** <code>optional string serverDate = 1;</code> */
    public String getServerDate() {
      Object ref = serverDate_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        serverDate_ = s;
        return s;
      }
    }

    /** <code>optional string serverDate = 1;</code> */
    public com.google.protobuf.ByteString getServerDateBytes() {
      Object ref = serverDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        serverDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      if (!getServerDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, serverDate_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getServerDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, serverDate_);
      }
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof RPCDateResponse)) {
        return super.equals(obj);
      }
      RPCDateResponse other = (RPCDateResponse) obj;

      boolean result = true;
      result = result && getServerDate().equals(other.getServerDate());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SERVERDATE_FIELD_NUMBER;
      hash = (53 * hash) + getServerDate().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public Builder newBuilderForType() {
      return newBuilder();
    }

    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    @Override
    public com.google.protobuf.Parser<RPCDateResponse> getParserForType() {
      return PARSER;
    }

    public RPCDateResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

    /**
     *
     *
     * <pre>
     * 定义相应内容
     * </pre>
     *
     * Protobuf type {@code grpc.RPCDateResponse}
     */
    public static final class Builder
        extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
        implements
        // @@protoc_insertion_point(builder_implements:grpc.RPCDateResponse)
        RPCDateResponseOrBuilder {
      private Object serverDate_ = "";

      // Construct using grpc.Test.RPCDateResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return Test.internal_static_grpc_RPCDateResponse_descriptor;
      }

      protected FieldAccessorTable internalGetFieldAccessorTable() {
        return Test.internal_static_grpc_RPCDateResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(RPCDateResponse.class, Builder.class);
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
      }

      public Builder clear() {
        super.clear();
        serverDate_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return Test.internal_static_grpc_RPCDateResponse_descriptor;
      }

      public RPCDateResponse getDefaultInstanceForType() {
        return RPCDateResponse.getDefaultInstance();
      }

      public RPCDateResponse build() {
        RPCDateResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public RPCDateResponse buildPartial() {
        RPCDateResponse result = new RPCDateResponse(this);
        result.serverDate_ = serverDate_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return super.clone();
      }

      public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
        return super.setField(field, value);
      }

      public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field, int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }

      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
        return super.addRepeatedField(field, value);
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RPCDateResponse) {
          return mergeFrom((RPCDateResponse) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RPCDateResponse other) {
        if (other == RPCDateResponse.getDefaultInstance()) return this;
        if (!other.getServerDate().isEmpty()) {
          serverDate_ = other.serverDate_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RPCDateResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RPCDateResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      /** <code>optional string serverDate = 1;</code> */
      public String getServerDate() {
        Object ref = serverDate_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          serverDate_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }

      /** <code>optional string serverDate = 1;</code> */
      public Builder setServerDate(String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        serverDate_ = value;
        onChanged();
        return this;
      }

      /** <code>optional string serverDate = 1;</code> */
      public com.google.protobuf.ByteString getServerDateBytes() {
        Object ref = serverDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          serverDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /** <code>optional string serverDate = 1;</code> */
      public Builder setServerDateBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        serverDate_ = value;
        onChanged();
        return this;
      }

      /** <code>optional string serverDate = 1;</code> */
      public Builder clearServerDate() {

        serverDate_ = getDefaultInstance().getServerDate();
        onChanged();
        return this;
      }

      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      // @@protoc_insertion_point(builder_scope:grpc.RPCDateResponse)
    }
  }

  // @@protoc_insertion_point(outer_class_scope)
}
