# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/test.proto',
  package='grpc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10proto/test.proto\x12\x04grpc\"\"\n\x0eRPCDateRequest\x12\x10\n\x08userName\x18\x01 \x01(\t\"%\n\x0fRPCDateResponse\x12\x12\n\nserverDate\x18\x01 \x01(\t2J\n\x0eRPCDateService\x12\x38\n\x07getDate\x12\x14.grpc.RPCDateRequest\x1a\x15.grpc.RPCDateResponse\"\x00\x62\x06proto3'
)




_RPCDATEREQUEST = _descriptor.Descriptor(
  name='RPCDateRequest',
  full_name='grpc.RPCDateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userName', full_name='grpc.RPCDateRequest.userName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=60,
)


_RPCDATERESPONSE = _descriptor.Descriptor(
  name='RPCDateResponse',
  full_name='grpc.RPCDateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='serverDate', full_name='grpc.RPCDateResponse.serverDate', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=99,
)

DESCRIPTOR.message_types_by_name['RPCDateRequest'] = _RPCDATEREQUEST
DESCRIPTOR.message_types_by_name['RPCDateResponse'] = _RPCDATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RPCDateRequest = _reflection.GeneratedProtocolMessageType('RPCDateRequest', (_message.Message,), {
  'DESCRIPTOR' : _RPCDATEREQUEST,
  '__module__' : 'proto.test_pb2'
  # @@protoc_insertion_point(class_scope:grpc.RPCDateRequest)
  })
_sym_db.RegisterMessage(RPCDateRequest)

RPCDateResponse = _reflection.GeneratedProtocolMessageType('RPCDateResponse', (_message.Message,), {
  'DESCRIPTOR' : _RPCDATERESPONSE,
  '__module__' : 'proto.test_pb2'
  # @@protoc_insertion_point(class_scope:grpc.RPCDateResponse)
  })
_sym_db.RegisterMessage(RPCDateResponse)



_RPCDATESERVICE = _descriptor.ServiceDescriptor(
  name='RPCDateService',
  full_name='grpc.RPCDateService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=101,
  serialized_end=175,
  methods=[
  _descriptor.MethodDescriptor(
    name='getDate',
    full_name='grpc.RPCDateService.getDate',
    index=0,
    containing_service=None,
    input_type=_RPCDATEREQUEST,
    output_type=_RPCDATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RPCDATESERVICE)

DESCRIPTOR.services_by_name['RPCDateService'] = _RPCDATESERVICE

# @@protoc_insertion_point(module_scope)
