# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import test_pb2 as proto_dot_test__pb2


class RPCDateServiceStub(object):
    """服务接口.定义请求参数和相应结果
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getDate = channel.unary_unary(
                '/grpc.RPCDateService/getDate',
                request_serializer=proto_dot_test__pb2.RPCDateRequest.SerializeToString,
                response_deserializer=proto_dot_test__pb2.RPCDateResponse.FromString,
                )


class RPCDateServiceServicer(object):
    """服务接口.定义请求参数和相应结果
    """

    def getDate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RPCDateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getDate': grpc.unary_unary_rpc_method_handler(
                    servicer.getDate,
                    request_deserializer=proto_dot_test__pb2.RPCDateRequest.FromString,
                    response_serializer=proto_dot_test__pb2.RPCDateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.RPCDateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RPCDateService(object):
    """服务接口.定义请求参数和相应结果
    """

    @staticmethod
    def getDate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.RPCDateService/getDate',
            proto_dot_test__pb2.RPCDateRequest.SerializeToString,
            proto_dot_test__pb2.RPCDateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
